//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.23 at 01:51:28 PM CEST 
//


package com.telefonica.ict.tools;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Consulta">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Solicitante">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Persona">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Fisica">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="NIF" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Apellido1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Apellido2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Direccion">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Numero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Descripcion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NombrePromotor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="NumeroViviendas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="NumeroOficinas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="NumeroLocales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="NumeroPlantas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="NumeroEscaleras" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="FechaInicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="FechaFin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Situacion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Direccion">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Coordenadas">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Huso" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="X" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Y" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="Latitud">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="Longitud">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DocumentoUbicacion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consulta"
})
@XmlRootElement(name = "COP")
public class COP {

    @XmlElement(name = "Consulta", required = true)
    protected COP.Consulta consulta;
    @XmlAttribute(name = "version")
    protected Byte version;

    /**
     * Gets the value of the consulta property.
     * 
     * @return
     *     possible object is
     *     {@link COP.Consulta }
     *     
     */
    public COP.Consulta getConsulta() {
        return consulta;
    }

    /**
     * Sets the value of the consulta property.
     * 
     * @param value
     *     allowed object is
     *     {@link COP.Consulta }
     *     
     */
    public void setConsulta(COP.Consulta value) {
        this.consulta = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setVersion(Byte value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Solicitante">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Persona">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Fisica">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="NIF" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Apellido1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Apellido2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Direccion">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Numero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Descripcion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NombrePromotor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="NumeroViviendas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="NumeroOficinas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="NumeroLocales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="NumeroPlantas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="NumeroEscaleras" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="FechaInicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="FechaFin" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Situacion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Direccion">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Coordenadas">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Huso" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="X" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="Y" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="Latitud">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="Longitud">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                       &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="DocumentoUbicacion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "solicitante",
        "descripcion",
        "situacion",
        "documentoUbicacion"
    })
    public static class Consulta {

        @XmlElement(name = "Solicitante", required = true)
        protected COP.Consulta.Solicitante solicitante;
        @XmlElement(name = "Descripcion", required = true)
        protected COP.Consulta.Descripcion descripcion;
        @XmlElement(name = "Situacion", required = true)
        protected COP.Consulta.Situacion situacion;
        @XmlElement(name = "DocumentoUbicacion", required = true)
        protected COP.Consulta.DocumentoUbicacion documentoUbicacion;

        /**
         * Gets the value of the solicitante property.
         * 
         * @return
         *     possible object is
         *     {@link COP.Consulta.Solicitante }
         *     
         */
        public COP.Consulta.Solicitante getSolicitante() {
            return solicitante;
        }

        /**
         * Sets the value of the solicitante property.
         * 
         * @param value
         *     allowed object is
         *     {@link COP.Consulta.Solicitante }
         *     
         */
        public void setSolicitante(COP.Consulta.Solicitante value) {
            this.solicitante = value;
        }

        /**
         * Gets the value of the descripcion property.
         * 
         * @return
         *     possible object is
         *     {@link COP.Consulta.Descripcion }
         *     
         */
        public COP.Consulta.Descripcion getDescripcion() {
            return descripcion;
        }

        /**
         * Sets the value of the descripcion property.
         * 
         * @param value
         *     allowed object is
         *     {@link COP.Consulta.Descripcion }
         *     
         */
        public void setDescripcion(COP.Consulta.Descripcion value) {
            this.descripcion = value;
        }

        /**
         * Gets the value of the situacion property.
         * 
         * @return
         *     possible object is
         *     {@link COP.Consulta.Situacion }
         *     
         */
        public COP.Consulta.Situacion getSituacion() {
            return situacion;
        }

        /**
         * Sets the value of the situacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link COP.Consulta.Situacion }
         *     
         */
        public void setSituacion(COP.Consulta.Situacion value) {
            this.situacion = value;
        }

        /**
         * Gets the value of the documentoUbicacion property.
         * 
         * @return
         *     possible object is
         *     {@link COP.Consulta.DocumentoUbicacion }
         *     
         */
        public COP.Consulta.DocumentoUbicacion getDocumentoUbicacion() {
            return documentoUbicacion;
        }

        /**
         * Sets the value of the documentoUbicacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link COP.Consulta.DocumentoUbicacion }
         *     
         */
        public void setDocumentoUbicacion(COP.Consulta.DocumentoUbicacion value) {
            this.documentoUbicacion = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NombrePromotor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="NumeroViviendas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="NumeroOficinas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="NumeroLocales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="NumeroPlantas" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="NumeroEscaleras" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="FechaInicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="FechaFin" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nombrePromotor",
            "numeroViviendas",
            "numeroOficinas",
            "numeroLocales",
            "numeroPlantas",
            "numeroEscaleras",
            "fechaInicio",
            "fechaFin"
        })
        public static class Descripcion {

            @XmlElement(name = "NombrePromotor", required = true)
            protected String nombrePromotor;
            @XmlElement(name = "NumeroViviendas")
            protected byte numeroViviendas;
            @XmlElement(name = "NumeroOficinas")
            protected byte numeroOficinas;
            @XmlElement(name = "NumeroLocales")
            protected byte numeroLocales;
            @XmlElement(name = "NumeroPlantas")
            protected byte numeroPlantas;
            @XmlElement(name = "NumeroEscaleras")
            protected byte numeroEscaleras;
            @XmlElement(name = "FechaInicio", required = true)
            protected String fechaInicio;
            @XmlElement(name = "FechaFin", required = true)
            protected String fechaFin;

            /**
             * Gets the value of the nombrePromotor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombrePromotor() {
                return nombrePromotor;
            }

            /**
             * Sets the value of the nombrePromotor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombrePromotor(String value) {
                this.nombrePromotor = value;
            }

            /**
             * Gets the value of the numeroViviendas property.
             * 
             */
            public byte getNumeroViviendas() {
                return numeroViviendas;
            }

            /**
             * Sets the value of the numeroViviendas property.
             * 
             */
            public void setNumeroViviendas(byte value) {
                this.numeroViviendas = value;
            }

            /**
             * Gets the value of the numeroOficinas property.
             * 
             */
            public byte getNumeroOficinas() {
                return numeroOficinas;
            }

            /**
             * Sets the value of the numeroOficinas property.
             * 
             */
            public void setNumeroOficinas(byte value) {
                this.numeroOficinas = value;
            }

            /**
             * Gets the value of the numeroLocales property.
             * 
             */
            public byte getNumeroLocales() {
                return numeroLocales;
            }

            /**
             * Sets the value of the numeroLocales property.
             * 
             */
            public void setNumeroLocales(byte value) {
                this.numeroLocales = value;
            }

            /**
             * Gets the value of the numeroPlantas property.
             * 
             */
            public byte getNumeroPlantas() {
                return numeroPlantas;
            }

            /**
             * Sets the value of the numeroPlantas property.
             * 
             */
            public void setNumeroPlantas(byte value) {
                this.numeroPlantas = value;
            }

            /**
             * Gets the value of the numeroEscaleras property.
             * 
             */
            public byte getNumeroEscaleras() {
                return numeroEscaleras;
            }

            /**
             * Sets the value of the numeroEscaleras property.
             * 
             */
            public void setNumeroEscaleras(byte value) {
                this.numeroEscaleras = value;
            }

            /**
             * Gets the value of the fechaInicio property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFechaInicio() {
                return fechaInicio;
            }

            /**
             * Sets the value of the fechaInicio property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFechaInicio(String value) {
                this.fechaInicio = value;
            }

            /**
             * Gets the value of the fechaFin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFechaFin() {
                return fechaFin;
            }

            /**
             * Sets the value of the fechaFin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFechaFin(String value) {
                this.fechaFin = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nombre",
            "hash"
        })
        public static class DocumentoUbicacion {

            @XmlElement(name = "Nombre", required = true)
            protected String nombre;
            @XmlElement(name = "Hash", required = true)
            protected String hash;

            /**
             * Gets the value of the nombre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombre() {
                return nombre;
            }

            /**
             * Sets the value of the nombre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombre(String value) {
                this.nombre = value;
            }

            /**
             * Gets the value of the hash property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHash() {
                return hash;
            }

            /**
             * Sets the value of the hash property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHash(String value) {
                this.hash = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Direccion">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Coordenadas">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Huso" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="X" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="Y" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="Latitud">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="Longitud">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                             &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "direccion",
            "coordenadas"
        })
        public static class Situacion {

            @XmlElement(name = "Direccion", required = true)
            protected COP.Consulta.Situacion.Direccion direccion;
            @XmlElement(name = "Coordenadas", required = true)
            protected COP.Consulta.Situacion.Coordenadas coordenadas;

            /**
             * Gets the value of the direccion property.
             * 
             * @return
             *     possible object is
             *     {@link COP.Consulta.Situacion.Direccion }
             *     
             */
            public COP.Consulta.Situacion.Direccion getDireccion() {
                return direccion;
            }

            /**
             * Sets the value of the direccion property.
             * 
             * @param value
             *     allowed object is
             *     {@link COP.Consulta.Situacion.Direccion }
             *     
             */
            public void setDireccion(COP.Consulta.Situacion.Direccion value) {
                this.direccion = value;
            }

            /**
             * Gets the value of the coordenadas property.
             * 
             * @return
             *     possible object is
             *     {@link COP.Consulta.Situacion.Coordenadas }
             *     
             */
            public COP.Consulta.Situacion.Coordenadas getCoordenadas() {
                return coordenadas;
            }

            /**
             * Sets the value of the coordenadas property.
             * 
             * @param value
             *     allowed object is
             *     {@link COP.Consulta.Situacion.Coordenadas }
             *     
             */
            public void setCoordenadas(COP.Consulta.Situacion.Coordenadas value) {
                this.coordenadas = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Huso" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="X" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="Y" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="Latitud">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="Longitud">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                   &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "huso",
                "x",
                "y",
                "latitud",
                "longitud"
            })
            public static class Coordenadas {

                @XmlElement(name = "Huso")
                protected byte huso;
                @XmlElement(name = "X")
                protected int x;
                @XmlElement(name = "Y")
                protected int y;
                @XmlElement(name = "Latitud", required = true)
                protected COP.Consulta.Situacion.Coordenadas.Latitud latitud;
                @XmlElement(name = "Longitud", required = true)
                protected COP.Consulta.Situacion.Coordenadas.Longitud longitud;

                /**
                 * Gets the value of the huso property.
                 * 
                 */
                public byte getHuso() {
                    return huso;
                }

                /**
                 * Sets the value of the huso property.
                 * 
                 */
                public void setHuso(byte value) {
                    this.huso = value;
                }

                /**
                 * Gets the value of the x property.
                 * 
                 */
                public int getX() {
                    return x;
                }

                /**
                 * Sets the value of the x property.
                 * 
                 */
                public void setX(int value) {
                    this.x = value;
                }

                /**
                 * Gets the value of the y property.
                 * 
                 */
                public int getY() {
                    return y;
                }

                /**
                 * Sets the value of the y property.
                 * 
                 */
                public void setY(int value) {
                    this.y = value;
                }

                /**
                 * Gets the value of the latitud property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link COP.Consulta.Situacion.Coordenadas.Latitud }
                 *     
                 */
                public COP.Consulta.Situacion.Coordenadas.Latitud getLatitud() {
                    return latitud;
                }

                /**
                 * Sets the value of the latitud property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link COP.Consulta.Situacion.Coordenadas.Latitud }
                 *     
                 */
                public void setLatitud(COP.Consulta.Situacion.Coordenadas.Latitud value) {
                    this.latitud = value;
                }

                /**
                 * Gets the value of the longitud property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link COP.Consulta.Situacion.Coordenadas.Longitud }
                 *     
                 */
                public COP.Consulta.Situacion.Coordenadas.Longitud getLongitud() {
                    return longitud;
                }

                /**
                 * Sets the value of the longitud property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link COP.Consulta.Situacion.Coordenadas.Longitud }
                 *     
                 */
                public void setLongitud(COP.Consulta.Situacion.Coordenadas.Longitud value) {
                    this.longitud = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "grados",
                    "direccion",
                    "minutos",
                    "segundos",
                    "decimales"
                })
                public static class Latitud {

                    @XmlElement(name = "Grados")
                    protected byte grados;
                    @XmlElement(name = "Direccion", required = true)
                    protected String direccion;
                    @XmlElement(name = "Minutos")
                    protected byte minutos;
                    @XmlElement(name = "Segundos")
                    protected byte segundos;
                    @XmlElement(name = "Decimales")
                    protected byte decimales;

                    /**
                     * Gets the value of the grados property.
                     * 
                     */
                    public byte getGrados() {
                        return grados;
                    }

                    /**
                     * Sets the value of the grados property.
                     * 
                     */
                    public void setGrados(byte value) {
                        this.grados = value;
                    }

                    /**
                     * Gets the value of the direccion property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDireccion() {
                        return direccion;
                    }

                    /**
                     * Sets the value of the direccion property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDireccion(String value) {
                        this.direccion = value;
                    }

                    /**
                     * Gets the value of the minutos property.
                     * 
                     */
                    public byte getMinutos() {
                        return minutos;
                    }

                    /**
                     * Sets the value of the minutos property.
                     * 
                     */
                    public void setMinutos(byte value) {
                        this.minutos = value;
                    }

                    /**
                     * Gets the value of the segundos property.
                     * 
                     */
                    public byte getSegundos() {
                        return segundos;
                    }

                    /**
                     * Sets the value of the segundos property.
                     * 
                     */
                    public void setSegundos(byte value) {
                        this.segundos = value;
                    }

                    /**
                     * Gets the value of the decimales property.
                     * 
                     */
                    public byte getDecimales() {
                        return decimales;
                    }

                    /**
                     * Sets the value of the decimales property.
                     * 
                     */
                    public void setDecimales(byte value) {
                        this.decimales = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Grados" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Minutos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Segundos" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *         &lt;element name="Decimales" type="{http://www.w3.org/2001/XMLSchema}byte"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "grados",
                    "direccion",
                    "minutos",
                    "segundos",
                    "decimales"
                })
                public static class Longitud {

                    @XmlElement(name = "Grados")
                    protected byte grados;
                    @XmlElement(name = "Direccion", required = true)
                    protected String direccion;
                    @XmlElement(name = "Minutos")
                    protected byte minutos;
                    @XmlElement(name = "Segundos")
                    protected byte segundos;
                    @XmlElement(name = "Decimales")
                    protected byte decimales;

                    /**
                     * Gets the value of the grados property.
                     * 
                     */
                    public byte getGrados() {
                        return grados;
                    }

                    /**
                     * Sets the value of the grados property.
                     * 
                     */
                    public void setGrados(byte value) {
                        this.grados = value;
                    }

                    /**
                     * Gets the value of the direccion property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDireccion() {
                        return direccion;
                    }

                    /**
                     * Sets the value of the direccion property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDireccion(String value) {
                        this.direccion = value;
                    }

                    /**
                     * Gets the value of the minutos property.
                     * 
                     */
                    public byte getMinutos() {
                        return minutos;
                    }

                    /**
                     * Sets the value of the minutos property.
                     * 
                     */
                    public void setMinutos(byte value) {
                        this.minutos = value;
                    }

                    /**
                     * Gets the value of the segundos property.
                     * 
                     */
                    public byte getSegundos() {
                        return segundos;
                    }

                    /**
                     * Sets the value of the segundos property.
                     * 
                     */
                    public void setSegundos(byte value) {
                        this.segundos = value;
                    }

                    /**
                     * Gets the value of the decimales property.
                     * 
                     */
                    public byte getDecimales() {
                        return decimales;
                    }

                    /**
                     * Sets the value of the decimales property.
                     * 
                     */
                    public void setDecimales(byte value) {
                        this.decimales = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tipoVia",
                "nombreVia",
                "ineProvincia",
                "ineMunicipio",
                "localidad",
                "cp"
            })
            public static class Direccion {

                @XmlElement(name = "TipoVia", required = true)
                protected String tipoVia;
                @XmlElement(name = "NombreVia", required = true)
                protected String nombreVia;
                @XmlElement(name = "INEProvincia")
                protected byte ineProvincia;
                @XmlElement(name = "INEMunicipio")
                protected byte ineMunicipio;
                @XmlElement(name = "Localidad", required = true)
                protected String localidad;
                @XmlElement(name = "CP")
                protected short cp;

                /**
                 * Gets the value of the tipoVia property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTipoVia() {
                    return tipoVia;
                }

                /**
                 * Sets the value of the tipoVia property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTipoVia(String value) {
                    this.tipoVia = value;
                }

                /**
                 * Gets the value of the nombreVia property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNombreVia() {
                    return nombreVia;
                }

                /**
                 * Sets the value of the nombreVia property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNombreVia(String value) {
                    this.nombreVia = value;
                }

                /**
                 * Gets the value of the ineProvincia property.
                 * 
                 */
                public byte getINEProvincia() {
                    return ineProvincia;
                }

                /**
                 * Sets the value of the ineProvincia property.
                 * 
                 */
                public void setINEProvincia(byte value) {
                    this.ineProvincia = value;
                }

                /**
                 * Gets the value of the ineMunicipio property.
                 * 
                 */
                public byte getINEMunicipio() {
                    return ineMunicipio;
                }

                /**
                 * Sets the value of the ineMunicipio property.
                 * 
                 */
                public void setINEMunicipio(byte value) {
                    this.ineMunicipio = value;
                }

                /**
                 * Gets the value of the localidad property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLocalidad() {
                    return localidad;
                }

                /**
                 * Sets the value of the localidad property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLocalidad(String value) {
                    this.localidad = value;
                }

                /**
                 * Gets the value of the cp property.
                 * 
                 */
                public short getCP() {
                    return cp;
                }

                /**
                 * Sets the value of the cp property.
                 * 
                 */
                public void setCP(short value) {
                    this.cp = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Persona">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Fisica">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="NIF" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Apellido1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="Apellido2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Direccion">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Numero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Telefono" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "persona",
            "direccion",
            "telefono",
            "email"
        })
        public static class Solicitante {

            @XmlElement(name = "Persona", required = true)
            protected COP.Consulta.Solicitante.Persona persona;
            @XmlElement(name = "Direccion", required = true)
            protected COP.Consulta.Solicitante.Direccion direccion;
            @XmlElement(name = "Telefono")
            protected int telefono;
            @XmlElement(name = "Email", required = true)
            protected String email;

            /**
             * Gets the value of the persona property.
             * 
             * @return
             *     possible object is
             *     {@link COP.Consulta.Solicitante.Persona }
             *     
             */
            public COP.Consulta.Solicitante.Persona getPersona() {
                return persona;
            }

            /**
             * Sets the value of the persona property.
             * 
             * @param value
             *     allowed object is
             *     {@link COP.Consulta.Solicitante.Persona }
             *     
             */
            public void setPersona(COP.Consulta.Solicitante.Persona value) {
                this.persona = value;
            }

            /**
             * Gets the value of the direccion property.
             * 
             * @return
             *     possible object is
             *     {@link COP.Consulta.Solicitante.Direccion }
             *     
             */
            public COP.Consulta.Solicitante.Direccion getDireccion() {
                return direccion;
            }

            /**
             * Sets the value of the direccion property.
             * 
             * @param value
             *     allowed object is
             *     {@link COP.Consulta.Solicitante.Direccion }
             *     
             */
            public void setDireccion(COP.Consulta.Solicitante.Direccion value) {
                this.direccion = value;
            }

            /**
             * Gets the value of the telefono property.
             * 
             */
            public int getTelefono() {
                return telefono;
            }

            /**
             * Sets the value of the telefono property.
             * 
             */
            public void setTelefono(int value) {
                this.telefono = value;
            }

            /**
             * Gets the value of the email property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmail() {
                return email;
            }

            /**
             * Sets the value of the email property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmail(String value) {
                this.email = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TipoVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="NombreVia" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Numero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="INEProvincia" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="INEMunicipio" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="Localidad" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="CP" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tipoVia",
                "nombreVia",
                "numero",
                "ineProvincia",
                "ineMunicipio",
                "localidad",
                "cp"
            })
            public static class Direccion {

                @XmlElement(name = "TipoVia", required = true)
                protected String tipoVia;
                @XmlElement(name = "NombreVia", required = true)
                protected String nombreVia;
                @XmlElement(name = "Numero")
                protected byte numero;
                @XmlElement(name = "INEProvincia")
                protected byte ineProvincia;
                @XmlElement(name = "INEMunicipio")
                protected byte ineMunicipio;
                @XmlElement(name = "Localidad", required = true)
                protected String localidad;
                @XmlElement(name = "CP")
                protected short cp;

                /**
                 * Gets the value of the tipoVia property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getTipoVia() {
                    return tipoVia;
                }

                /**
                 * Sets the value of the tipoVia property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setTipoVia(String value) {
                    this.tipoVia = value;
                }

                /**
                 * Gets the value of the nombreVia property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNombreVia() {
                    return nombreVia;
                }

                /**
                 * Sets the value of the nombreVia property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNombreVia(String value) {
                    this.nombreVia = value;
                }

                /**
                 * Gets the value of the numero property.
                 * 
                 */
                public byte getNumero() {
                    return numero;
                }

                /**
                 * Sets the value of the numero property.
                 * 
                 */
                public void setNumero(byte value) {
                    this.numero = value;
                }

                /**
                 * Gets the value of the ineProvincia property.
                 * 
                 */
                public byte getINEProvincia() {
                    return ineProvincia;
                }

                /**
                 * Sets the value of the ineProvincia property.
                 * 
                 */
                public void setINEProvincia(byte value) {
                    this.ineProvincia = value;
                }

                /**
                 * Gets the value of the ineMunicipio property.
                 * 
                 */
                public byte getINEMunicipio() {
                    return ineMunicipio;
                }

                /**
                 * Sets the value of the ineMunicipio property.
                 * 
                 */
                public void setINEMunicipio(byte value) {
                    this.ineMunicipio = value;
                }

                /**
                 * Gets the value of the localidad property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLocalidad() {
                    return localidad;
                }

                /**
                 * Sets the value of the localidad property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLocalidad(String value) {
                    this.localidad = value;
                }

                /**
                 * Gets the value of the cp property.
                 * 
                 */
                public short getCP() {
                    return cp;
                }

                /**
                 * Sets the value of the cp property.
                 * 
                 */
                public void setCP(short value) {
                    this.cp = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Fisica">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="NIF" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Apellido1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="Apellido2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fisica"
            })
            public static class Persona {

                @XmlElement(name = "Fisica", required = true)
                protected COP.Consulta.Solicitante.Persona.Fisica fisica;

                /**
                 * Gets the value of the fisica property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link COP.Consulta.Solicitante.Persona.Fisica }
                 *     
                 */
                public COP.Consulta.Solicitante.Persona.Fisica getFisica() {
                    return fisica;
                }

                /**
                 * Sets the value of the fisica property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link COP.Consulta.Solicitante.Persona.Fisica }
                 *     
                 */
                public void setFisica(COP.Consulta.Solicitante.Persona.Fisica value) {
                    this.fisica = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="NIF" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Nombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Apellido1" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="Apellido2" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "nif",
                    "nombre",
                    "apellido1",
                    "apellido2"
                })
                public static class Fisica {

                    @XmlElement(name = "NIF", required = true)
                    protected String nif;
                    @XmlElement(name = "Nombre", required = true)
                    protected String nombre;
                    @XmlElement(name = "Apellido1", required = true)
                    protected String apellido1;
                    @XmlElement(name = "Apellido2", required = true)
                    protected String apellido2;

                    /**
                     * Gets the value of the nif property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNIF() {
                        return nif;
                    }

                    /**
                     * Sets the value of the nif property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNIF(String value) {
                        this.nif = value;
                    }

                    /**
                     * Gets the value of the nombre property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNombre() {
                        return nombre;
                    }

                    /**
                     * Sets the value of the nombre property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNombre(String value) {
                        this.nombre = value;
                    }

                    /**
                     * Gets the value of the apellido1 property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getApellido1() {
                        return apellido1;
                    }

                    /**
                     * Sets the value of the apellido1 property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setApellido1(String value) {
                        this.apellido1 = value;
                    }

                    /**
                     * Gets the value of the apellido2 property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getApellido2() {
                        return apellido2;
                    }

                    /**
                     * Sets the value of the apellido2 property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setApellido2(String value) {
                        this.apellido2 = value;
                    }

                }

            }

        }

    }

}
