//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-146 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.23 at 01:51:28 PM CEST 
//


package com.telefonica.ict.tools;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.telefonica.ict.tools package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.telefonica.ict.tools
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link COP.Consulta.Solicitante.Persona }
     * 
     */
    public COP.Consulta.Solicitante.Persona createCOPConsultaSolicitantePersona() {
        return new COP.Consulta.Solicitante.Persona();
    }

    /**
     * Create an instance of {@link COP.Consulta }
     * 
     */
    public COP.Consulta createCOPConsulta() {
        return new COP.Consulta();
    }

    /**
     * Create an instance of {@link COP.Consulta.DocumentoUbicacion }
     * 
     */
    public COP.Consulta.DocumentoUbicacion createCOPConsultaDocumentoUbicacion() {
        return new COP.Consulta.DocumentoUbicacion();
    }

    /**
     * Create an instance of {@link COP.Consulta.Situacion.Direccion }
     * 
     */
    public COP.Consulta.Situacion.Direccion createCOPConsultaSituacionDireccion() {
        return new COP.Consulta.Situacion.Direccion();
    }

    /**
     * Create an instance of {@link COP }
     * 
     */
    public COP createCOP() {
        return new COP();
    }

    /**
     * Create an instance of {@link COP.Consulta.Solicitante }
     * 
     */
    public COP.Consulta.Solicitante createCOPConsultaSolicitante() {
        return new COP.Consulta.Solicitante();
    }

    /**
     * Create an instance of {@link COP.Consulta.Situacion.Coordenadas.Latitud }
     * 
     */
    public COP.Consulta.Situacion.Coordenadas.Latitud createCOPConsultaSituacionCoordenadasLatitud() {
        return new COP.Consulta.Situacion.Coordenadas.Latitud();
    }

    /**
     * Create an instance of {@link COP.Consulta.Solicitante.Persona.Fisica }
     * 
     */
    public COP.Consulta.Solicitante.Persona.Fisica createCOPConsultaSolicitantePersonaFisica() {
        return new COP.Consulta.Solicitante.Persona.Fisica();
    }

    /**
     * Create an instance of {@link COP.Consulta.Situacion }
     * 
     */
    public COP.Consulta.Situacion createCOPConsultaSituacion() {
        return new COP.Consulta.Situacion();
    }

    /**
     * Create an instance of {@link COP.Consulta.Situacion.Coordenadas.Longitud }
     * 
     */
    public COP.Consulta.Situacion.Coordenadas.Longitud createCOPConsultaSituacionCoordenadasLongitud() {
        return new COP.Consulta.Situacion.Coordenadas.Longitud();
    }

    /**
     * Create an instance of {@link COP.Consulta.Descripcion }
     * 
     */
    public COP.Consulta.Descripcion createCOPConsultaDescripcion() {
        return new COP.Consulta.Descripcion();
    }

    /**
     * Create an instance of {@link COP.Consulta.Situacion.Coordenadas }
     * 
     */
    public COP.Consulta.Situacion.Coordenadas createCOPConsultaSituacionCoordenadas() {
        return new COP.Consulta.Situacion.Coordenadas();
    }

    /**
     * Create an instance of {@link COP.Consulta.Solicitante.Direccion }
     * 
     */
    public COP.Consulta.Solicitante.Direccion createCOPConsultaSolicitanteDireccion() {
        return new COP.Consulta.Solicitante.Direccion();
    }

}
